# SITE INFORMATIONS
# -------------------------------------------------------------------------

site_name: Plateforme de ressources ouvertes
site_author: (à renseigner)
site_description: (à renseigner)





# LANGUE ET COULEURS 
# -------------------------------------------------------------------------

theme:
    language: fr
    palette:
        primary: green            # Couleurs pincipales
        accent: blue              # Couleur de surbrillance

# [Liste des couleurs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color)






# MENTIONS 
# -------------------------------------------------------------------------

copyright: Konsilion - Licence juridique Creative Commons CC-BY-NC 4.0  # Renseigner ce que vous voulez ici







      
 





# ============  /!\ NE PAS MODIFIER /!\ - procedure d'appel du fichier env pour le paramètrage  ============

INHERIT: ./docs/env  