# BIENVENU ! MODIFIER ICI LES PARAMETRES DE VOTRE PLATEFORME KATALOG
# --------------------------------------------------------------------------------------------------------------------------------------------------
#
# Konsilion - Licence juridique Creative Commons CC-BY-NC
# --------------------------------------------------------------------------------------------------------------------------------------------------



# SITE INFORMATIONS 
# --------------------------------------------------------------------------------------------------------------------------------------------------

site_name: Katalog - Plateforme de ressources ouvertes
site_author: (à renseigner)
site_description: (à renseigner)




# LANGUE ET COULEURS 
# --------------------------------------------------------------------------------------------------------------------------------------------------

theme:
    language: fr
    palette:
        primary: blue
        accent: blue

# [Liste des couleurs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color)





# MENTIONS 
# --------------------------------------------------------------------------------------------------------------------------------------------------

copyright: Konsilion - Licence juridique Creative Commons CC-BY-NC 4.0





# DERNIERE ETAPE
# --------------------------------------------------------------------------------------------------------------------------------------------------

# Il vous faut modifier le fichier 'parametres.csv' se trouvant dans le dossier 'docs/parametres.csv'.

# Ce dernier donne la localisation de votre plateforme dans le Web

# --------------------------------------------------------------------------------------------------------------------------------------------------


      
 



















# ============  /!\ NE PAS MODIFIER /!\ - procedure d'appel du fichier 'env' pour le parametrage  ============

INHERIT: ./docs/etc/env  