
# ============== NE PAS MODIFIER CETTE PAGE ==============


INHERIT: ./docs/env

nav:

    - Bibliothèques: biblioteks/home.md
    
    - Espaces de stockages: stockages/home.md

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    
  logo: ./images/logo.png
  favicon: ./images/logo.png

plugins:
  - macros
  - mike

markdown_extensions:
  - toc:
      permalink: true
  - md_in_html
  - footnotes
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.details

extra_css:
  - https://konsilion.github.io/katalog-setup/css/extra.css